github.com:
    users:
        brightonjosephkbj:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: brightonjosephkbj
